### ISSUE TITLE
Add column "Displayed in the Browser" to the tracker

### ISSUE THREAD

**Issue by zperova** [HumanCellAtlas/data-monitoring-dashboard#14]
As a data wrangler, I would like the tracker to show which datasets are currently displayed in the Browser.

I suggest adding a column "Displayed in Browser" (or something similar) to the tracker, where a yes/no value is expected.

**Comment by parthshahva** [comment]
@zperova Isn't this already accounted for? Azul is the service that feeds the presentation data in the browser. If you sort by the Azul columns, you will see exactly which projects and how many bundles are displayed in the browser

**Comment by zperova** [comment]
@parthshahva you are right, it is. I guess the issue is actually not the column but the dataset name in the Project short name - the confusing part (for me) is that it is different from the full name in the Browser (for many of them). Some of these short names are a bit too cryptic as we don't have any rules/guidelines for contributors in their choice of the project short name. 

Is this the public tracker? 
Would it be possible to display the full name of the project instead of the project short_name as a short term solution? At least there will be more consistency as some contributors put the full name of the project into the project_short_name column. For the long term, we will need to decide on guidelines/rules as to what the short_name of the project should be (we also have an alias that the wranglers create in our own documentation which is the third possible name for the same dataset - making it even more confusing).

**Comment by parthshahva** [comment]
Project short name and title are now both visible in the tracker
