### ISSUE TITLE
Add column "Submitted by"

### ISSUE THREAD

**Issue by zperova** [HumanCellAtlas/data-monitoring-dashboard#15]
As a data wrangler, I would like to see which wrangler has submitted a particular dataset in the tracker. 

Could this be pulled from the authentication information when we log into the UI to submit?

**Comment by rexwangcc** [comment]
At this moment, I think the submission does not carry the wrangler information. (correct me if I'm wrong). An easy way to implement this in the data-monitoring-dashboard, without adding extra states to the submissions, might be maintaining a "lookup" table somewhere this dashboard can check and map for you.

**Comment by parthshahva** [comment]
So unfortunately the submission in ingest api only has a reference to some unusable auth entity like "user" : "google-oauth2|110548651158605123831". I don't see a way to turn this into a usable field at this moment. Maybe one of the ingest devs knows

**Comment by parthshahva** [comment]
Wranglers and PIs are now available
