### ISSUE TITLE
Enable sorting in order and sorting of multiple columns

### ISSUE THREAD

**Issue by zperova** [HumanCellAtlas/data-monitoring-dashboard#16]
As a data wrangler, I would like to be able to sort datasets in Increasing and Decreasing order and also sort by multiple columns.

Currently, the little triangles (supposedly indicating the order of sorting) have the same effect - when I click on it next to "Azul Primary bundles indexed" it puts the dataset with 0 bundles at the top of the list.
I would like to be able to specify Increasing or Decreasing order.

Also, I would like to be able to then sort datasets by the Submission date.

**Comment by parthshahva** [comment]
Hi @zperova currently you cannot sort by multiple columns but have you tried clicking on the column multiple times. If you click it once, it becomes ascending order. If you click it again, it becomes descending order. This should allow you to flip the order when searching by the counts and submission dates. Let me know if this is not working

**Comment by zperova** [comment]
@parthshahva thanks, I am doing that. I guess the functionality of the triangles is only relevant when the multiple columns sorting is possible. It would be nice if that could be implemented eventually.

**Comment by parthshahva** [comment]
Hi @zperova, sorting by multiple columns is already supported. If you press shift while clicking on multiple columns, it will retain all prior sorting selections. If you don't press shift, it will override prior selections and sort by only the last selected column.
