### ISSUE TITLE
Add option to filter out projects that have been tombstoned

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/data-monitoring-dashboard#18]
As an admin of the system I would like to look at the tracker to see the legitimate projects in the system and I do not want to see projects that have had all their data deleted from the data store. Many projects have been ingested multiple times. These extra copies of projects confuse the view of the system and make it harder to see the state of the system.

**Comment by parthshahva** [comment]
All projects with no data in dss, azul, matrix are now hidden from the view. This should help make the view more useable
