### ISSUE TITLE
Add column "Publications"

### ISSUE THREAD

**Issue by zperova** [HumanCellAtlas/data-monitoring-dashboard#48]
As a wrangler, I would like to see whether the dataset has a publication mentioned in the spreadsheet to filter those datasets that need AUDR for a publication title.

Populate the column with `project.publications.publication_title` and ideally add a link from `project.publications.publication_url`

**Comment by parthshahva** [comment]
I think its best to use the data store or azul for this. The data tracker should not overload with metadata and columns. This field is not very useful from a data ops/monitoring perspective imo. I'm closing this ticket but feel free to re-open if you disagree.
