### ISSUE TITLE
Fix bug about duplicated Ingest submission IDs

### ISSUE THREAD

**Issue by ESapenaVentura** [HumanCellAtlas/data-monitoring-dashboard#54]
There is a bug in which the submission IDs are shown twice per each submission.
An example can be seen on the [Mouse gastrulation atlas]( https://tracker.data.humancellatlas.org/?projectUUID=1defdada-a365-44ad-9b29-443b06bd11d6) project, which should only be 1 submission. 

(PS; thanks for the update, it is really useful!)

**Comment by parthshahva** [comment]
This is now fixed. Please do a hard refresh so you pick up the updated javascript. Thanks for the bug report.
