### ISSUE TITLE
Add tsv output download button to data monitoring dashboard

### ISSUE THREAD

**Issue by mshadbolt** [HumanCellAtlas/data-monitoring-dashboard#55]
@mshadbolt commented on [Wed Oct 02 2019](https://github.com/HumanCellAtlas/upload-service/issues/403)

As a data wrangler I would like the ability to download a tabular format of the information in the data tracker so that I can easily calculate statistics and create visualisations, ideally as a download link on the tracker website.

Currently copying and pasting the data produces a table that is not easy to use, there are merged cells and information is not separated into columns.

Alternative would be to point me at the code that grabs the data and I can adapt it for my purposes.

Thanks!

**Comment by parthshahva** [comment]
Hi @mshadbolt all the data is available via API at tracker-api https://tracker-api.data.humancellatlas.org/v0/projects. Does this meet your needs or are you still requesting an export button?

**Comment by mshadbolt** [comment]
Ok cool I can probably work with that I will check it out, thanks!
